- Numpy 线性代数和随机数处理等
- scipy核心库 有效计算numpy矩阵
- matplotlib 基于numpy
- pandas 基于scipy和numpy，具有高效的series和dataframe数据结构

ndarray 有丰富的函数
- 维度称为轴，轴的个数成为秩
- 基本属性
 · ndarray.ndim 秩
 · ndarray.shape 维度
 · ndarray.size 元素总个数
 · ndarray.dtype 元素类型
 · ndarray.itemsize 元素字节大小

In [8]:
import numpy as np
aArray = np.array([1,2,3])
bArray = np.array([(1,2,3),(4,5,6)])
print(aArray)
print(bArray)
print(np.arange(1,5,0.5))
print(np.random.random((2,2)))
print(np.linspace(1,2,10,endpoint=False))

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[[0.02544498 0.39981605]
 [0.14797923 0.27273083]]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [15]:
import numpy as np
c = np.fromfunction(lambda i,j:(i+1)*(j+1),(9,9))
print(c)
print(c.ndim)
print(c.shape)
print(c.size)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 9. 18. 27. 36. 45. 54. 63. 72. 81.]]
2
(9, 9)
81


In [17]:
import numpy as np
a = np.arange(1,5,dtype=np.float64)
x = np.power(a, 2).sum()
print(x)
y = np.add(a, np.arange(4))
print(y)

30.0
[1. 3. 5. 7.]
